{ lib, ... }:
{
  # setup systemd for lima vm.
  services.lima.enable = true;

  # required by lima vm to function properly.
  security.sudo.wheelNeedsPassword = false;
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "yes";
  users.users.root.password = "nixos";

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  # https://github.com/nixos-lima/nixos-lima-config-sample/blob/e3c5900812e81343e018dad8812a1d44cd2bee7b/nixos-lima-config.nix#L33
  boot.loader.grub = {
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
    device = lib.mkForce "/dev/vda1"; # /dev/disk/by-label/ESP
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ];
  };
}
